#!/usr/bin/env python3
"""Redirect registry module sources to this checkout so CI can init without a token.

Examples in this repository reference the published registry address,
app.terraform.io/WebbPulse/platform-modules/aws//modules/<name>, because that is what a
real consumer writes. Resolving that address needs an HCP Terraform API token, and CI
runs with no credentials of any kind. Terraform's override-file mechanism lets a
generated _ci_override.tf replace just the source and version arguments of each module
block, pointing them at ../../modules/<name> in this checkout.

That is strictly better than fetching the published version: the pull request gets
validated against the module code it actually changes, not against the last release.
The override file is generated at validate time and never committed.
"""

import pathlib
import re
import sys

REGISTRY = "app.terraform.io/WebbPulse/platform-modules/aws//modules/"

# Matches: module "name" { ... source = "<registry>/<module>" ... }
# The source line is found within the block by scanning forward, so argument order
# inside the block does not matter.
MODULE_START = re.compile(r'^\s*module\s+"([^"]+)"\s*\{')
SOURCE_LINE = re.compile(r'^\s*source\s*=\s*"' + re.escape(REGISTRY) + r'([^"]+)"')


def find_registry_modules(text):
    """Return [(module_label, module_name)] for every registry-sourced module block."""
    found = []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        start = MODULE_START.match(lines[i])
        if not start:
            i += 1
            continue
        label = start.group(1)
        depth = lines[i].count("{") - lines[i].count("}")
        j = i + 1
        while j < len(lines) and depth > 0:
            src = SOURCE_LINE.match(lines[j])
            if src and depth == 1:
                found.append((label, src.group(1)))
            depth += lines[j].count("{") - lines[j].count("}")
            j += 1
        i = j
    return found


def main():
    example_dir = pathlib.Path(sys.argv[1]).resolve()
    repo_root = pathlib.Path(sys.argv[2]).resolve()

    modules = []
    for tf in sorted(example_dir.glob("*.tf")):
        if tf.name == "_ci_override.tf":
            continue
        modules.extend(find_registry_modules(tf.read_text()))

    if not modules:
        return 0

    rel = pathlib.Path("../..") / "modules"
    body = [
        "# Generated by .github/scripts/local_module_override.py for CI validation only.",
        "# Points registry module sources at this checkout so terraform init needs no token.",
        "",
    ]
    for label, name in modules:
        body.append(f'module "{label}" {{')
        body.append(f'  source = "{rel.as_posix()}/{name}"')
        # version is meaningless for a local path source and Terraform rejects the pair,
        # so the override clears it.
        body.append("  version = null")
        body.append("}")
        body.append("")

    (example_dir / "_ci_override.tf").write_text("\n".join(body))
    print(f"{example_dir.name}: overrode {len(modules)} registry module source(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
